[project]
name = "flood-data-ecosystem-assam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.2",
    "python-dotenv>=1.1.1",
]
